# Security Monitor Configuration

security_detection:
  update_rate: 1.0  # Hz
  confidence_threshold: 0.7
  timeout: 5.0  # seconds

threat_classification:
  threat_levels:
    none: 0.0
    low: 0.2
    medium: 0.4
    high: 0.6
    critical: 0.8
  
  classification_timeout: 0.1  # seconds

emergency_handling:
  critical_threshold: 0.8
  high_threshold: 0.6
  emergency_stop_enabled: true
  alert_timeout: 5.0  # seconds

sensor_monitoring:
  camera_timeout: 1.0  # seconds
  lidar_timeout: 1.0   # seconds
  sensor_health_check_rate: 2.0  # Hz

# Performance Monitoring Configuration
performance_monitoring:
  cpu_threshold: 80.0  # percentage
  memory_threshold: 85.0  # percentage
  latency_threshold: 100.0  # milliseconds
  monitoring_rate: 1.0  # Hz
  
# Model Management Configuration
model_management:
  yolo_model_path: "models/yolo/yolov8n.pt"
  pointpillars_model_path: "models/pointpillars/pointpillars.pth"
  model_health_check_rate: 0.2  # Hz
  performance_threshold: 0.8

# Error Handling Configuration
error_handling:
  error_reporting_enabled: true
  critical_error_threshold: 5
  error_logging_level: "INFO"
  system_health_check_rate: 0.2  # Hz
  
# System Optimization Configuration
system_optimization:
  optimization_enabled: true
  optimization_interval: 30.0  # seconds
  performance_threshold: 0.8
  auto_tuning_enabled: true
